drop table if exists bi.`MOM_ABNORMAL_TASK`;
CREATE TABLE bi.`MOM_ABNORMAL_TASK` (
  `CID` bigint NOT NULL COMMENT "对象",
  `CREMARK` varchar(1024) NULL COMMENT "备注",
  `CSOFT_DELETE_FLAG` int NULL COMMENT "软删除标记",
  `CCREATOR_ID` bigint NULL COMMENT "创建者ID",
  `CCREATOR_ENTITY_TYPE` varchar(255) NULL,
  `CPROMISE_RESOLUTION_TIME` datetime NULL COMMENT "承诺解决时间",
  `CHANDLER_ENTITY_TYPE` varchar(256) NULL,
  `CFACTORY_ENTITY_TYPE` varchar(256) NULL,
  `CQEQUIP_ENTITY_TYPE` varchar(256) NULL,
  `CCLOSE_TIME` datetime NULL COMMENT "关闭时间",
  `CCREATE_TIME` datetime NULL COMMENT "创建时间",
  `CABNORMAL_DESC` varchar(2000) NULL COMMENT "异常描述",
  `CCODE` varchar(512) NULL COMMENT "编码",
  `CLATEST_UPDATE_TIME` datetime NULL COMMENT "最近修改时间",
  `CMODIFIER_ID` bigint NULL COMMENT "修改者ID",
  `CENTITY_TYPE` varchar(256) NULL COMMENT "实体类型",
  `CPROCESS_MEASURES` varchar(4000) NULL COMMENT "处理措施",
  `CABNORMAL_CATEGORY_ID` bigint NULL COMMENT "异常类别ID",
  `CABNORMAL_CATEGORY_ENTITY_TYPE` varchar(256) NULL,
  `CENV` varchar(80) NULL COMMENT "环境标识",
  `CCLOSER_ID` bigint NULL COMMENT "关闭人ID",
  `CREQUIRED_FINISH_TIME` datetime NULL COMMENT "需求解决时间",
  `CQEQUIP_ID` bigint NULL,
  `CABNORMAL_CAUSE` varchar(4000) NULL COMMENT "异常原因",
  `CHANDLER_ID` bigint NULL COMMENT "处理人	ID",
  `CSECURITY_LEVEL` varchar(256) NULL COMMENT "密级",
  `CINITIATOR_ENTITY_TYPE` varchar(256) NULL,
  `CJOIN_FLOW_FLAG` varchar(1) NULL COMMENT "是否加入审批流",
  `CNAME` varchar(512) NULL COMMENT "名称",
  `CPROCESS_INSTANCE_ID` varchar(256) NULL COMMENT "所属流程",
  `CFACTORY_ID` bigint NULL COMMENT "所属工厂ID",
  `CFACTORY_NAME` varchar(256) NULL COMMENT "工厂名称",
  `CBIZ_ORG_ID` bigint NULL COMMENT "工厂组织ID",
  `CBIZ_ORG_NAME` varchar(256) NULL COMMENT "工厂组织名称",
  `CEQUIP_ID` bigint NULL COMMENT "设备ID",
  `CBIZ_ORG_ENTITY_TYPE` varchar(256) NULL,
  `CLIFECYCLE_STATE` varchar(256) NULL COMMENT "异常状态 [APT_PROCESSED:已处理, APT_PROCESSING:处理中, APT_PENDING:待处理, APT_CLOSED:已关闭]",
  `CLIFECYCLE_TEMPLATE` varchar(256) NULL COMMENT "生命周期模板",
  `CEQUIP_ENTITY_TYPE` varchar(256) NULL,
  `CPROCESS_KEY` varchar(512) NULL COMMENT "流程编码",
  `CUSERID` varchar(256) NULL COMMENT "发起人",
  `CLIFECYCLE_STATE_TYPE` varchar(256) NULL COMMENT "生命周期阶段 [OBSOLETE:废弃, RELEASE:发布, ACTIVE:活动, CREATE:创建]",
  `CINITIATOR_ID` bigint NULL COMMENT "发起人ID",
  `CCLOSER_ENTITY_TYPE` varchar(256) NULL,
  `CMODIFIER_ENTITY_TYPE` varchar(255) NULL,
  `CCLOSURE_EXPLANATION` varchar(4000) NULL COMMENT "关闭说明",
  `CLOG_PROCESS_TIME` datetime null COMMENT "日志处理时间",
  `CLOG_INITIATE_TIME` datetime null COMMENT "日志创建时间",
  `CLOG_CLOSE_TIME` datetime null COMMENT "日志关闭时间"
) ENGINE=OLAP
UNIQUE KEY(`CID`)
COMMENT '异常任务'
DISTRIBUTED BY HASH(`CID`) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"min_load_replica_num" = "-1",
"is_being_synced" = "false",
"storage_medium" = "hdd",
"storage_format" = "V2",
"inverted_index_storage_format" = "V2",
"compression" = "LZ4",
"enable_unique_key_merge_on_write" = "true",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false",
"group_commit_interval_ms" = "10000",
"group_commit_data_bytes" = "134217728",
"enable_mow_light_delete" = "false"
);

insert into bi.`MOM_ABNORMAL_TASK`  
select t1.`CID`
  , t1.`CREMARK`
  , t1.`CSOFT_DELETE_FLAG`
  , t1.`CCREATOR_ID`
  , t1.`CCREATOR_ENTITY_TYPE`
  , t1.`CPROMISE_RESOLUTION_TIME`
  , t1.`CHANDLER_ENTITY_TYPE`
  , t1.`CFACTORY_ENTITY_TYPE`
  , t1.`CQEQUIP_ENTITY_TYPE`
  , t1.`CCLOSE_TIME`
  , t1.`CCREATE_TIME`
  , t1.`CABNORMAL_DESC`
  , t1.`CCODE`
  , t1.`CLATEST_UPDATE_TIME`
  , t1.`CMODIFIER_ID`
  , t1.`CENTITY_TYPE`
  , t1.`CPROCESS_MEASURES`
  , t1.`CABNORMAL_CATEGORY_ID`
  , t1.`CABNORMAL_CATEGORY_ENTITY_TYPE`
  , t1.`CENV`
  , t1.`CCLOSER_ID`
  , t1.`CREQUIRED_FINISH_TIME`
  , t1.`CQEQUIP_ID`
  , t1.`CABNORMAL_CAUSE`
  , t1.`CHANDLER_ID`
  , t1.`CSECURITY_LEVEL`
  , t1.`CINITIATOR_ENTITY_TYPE`
  , t1.`CJOIN_FLOW_FLAG`
  , t1.`CNAME`
  , t1.`CPROCESS_INSTANCE_ID`
  , t1.`CFACTORY_ID`
  , t4.`CNAME` as `CFACTORY_NAME`
  , t1.`CBIZ_ORG_ID`
  , t3.`CNAME` as `CBIZ_ORG_NAME`
  , t1.`CEQUIP_ID`
  , t1.`CBIZ_ORG_ENTITY_TYPE`
  , t1.`CLIFECYCLE_STATE`
  , t1.`CLIFECYCLE_TEMPLATE`
  , t1.`CEQUIP_ENTITY_TYPE`
  , t1.`CPROCESS_KEY`
  , t1.`CUSERID`
  , t1.`CLIFECYCLE_STATE_TYPE`
  , t1.`CINITIATOR_ID`
  , t1.`CCLOSER_ENTITY_TYPE`
  , t1.`CMODIFIER_ENTITY_TYPE`
  , t1.`CCLOSURE_EXPLANATION`
  , t2.CPROCESS_TIME
  , t2.CINITIATE_TIME
  , t2.CCLOSE_TIME
from target.`MOM_ABNORMAL_TASK` t1
INNER JOIN (SELECT CSOURCE_ID AS CID,
MIN(CASE COPERATION_TYPE WHEN 'PROCESS' THEN COPERATION_TIME END) as CPROCESS_TIME,
MAX(CASE COPERATION_TYPE WHEN 'INITIATE' THEN COPERATION_TIME END) as CINITIATE_TIME,
MAX(CASE COPERATION_TYPE WHEN 'CLOSE' THEN COPERATION_TIME END) as CCLOSE_TIME
FROM target.MOM_ABNORMAL_TASK_LOG_LINK
GROUP by CSOURCE_ID) t2
ON t1.CID = t2.CID
LEFT JOIN target.SYS_BIZ_ORG t3 ON t1.CBIZ_ORG_ID = t3.CID
LEFT JOIN target.SYS_BIZ_ORG t4 ON t1.CFACTORY_ID = t4.CID
where t1.CSOFT_DELETE_FLAG=0