CREATE DATABASE IF NOT EXISTS bi;
DROP TABLE IF EXISTS bi.MOM_MANU_ORDER_WIDE;
CREATE TABLE IF NOT EXISTS bi.MOM_MANU_ORDER_WIDE (
  CID bigint NOT NULL COMMENT "对象",
  CMATERIAL_ENTITY_TYPE varchar(256) NULL,
  CBOM_ENTITY_TYPE varchar(256) NULL,
  CSCHEDULED_FLAG varchar(1) NULL COMMENT "排程标记",
  CPROD_ORDER_ENTITY_TYPE varchar(256) NULL,
  CMATERIAL_ID bigint NULL COMMENT "物料ID",
  CBATCH_NUMBER varchar(256) NULL COMMENT "批次号",
  CPROJECT_NUMBER varchar(256) NULL,
  CFACTORY_ID bigint NULL COMMENT "所属工厂ID",
  CFACTORY_NAME varchar(512) NULL COMMENT "所属工厂ID",
  COUTSOURCING_FLAG varchar(1) NULL COMMENT "是否外委",
  CFACTORY_ENTITY_TYPE varchar(256) NULL,
  CPRIORITY int NULL COMMENT "优先级",
  CSPLIT_CARD_FLAG varchar(1) NULL COMMENT "分卡标记",
  CACTUAL_END_TIME datetime NULL COMMENT "实际结束时间",
  CPREPARATION_PLAN_ENTITY_TYPE varchar(256) NULL,
  CPREPARATION_PLAN_ID bigint NULL COMMENT "物料准备计划ID",
  CPLANNER_ID bigint NULL COMMENT "计划员ID",
  CDRAWING_NUMBER varchar(512) NULL,
  CSCRAPPED_QTY decimal(38,9) NULL COMMENT "报废数量",
  CCREATE_TIME datetime NULL COMMENT "创建时间",
  CCREATOR_ID bigint NULL COMMENT "创建者ID",
  CPLANNED_START_TIME datetime NULL COMMENT "计划开始时间",
  CCREATOR_ENTITY_TYPE varchar(256) NULL,
  CENV varchar(80) NULL COMMENT "环境标识",
  CQUALIFIED_QTY decimal(38,9) NULL COMMENT "合格数量",
  CMANU_MODEL varchar(256) NULL COMMENT "制造型号",
  CPLANNED_QTY decimal(38,9) NULL COMMENT "计划数量",
  CSCHEDULED_START_TIME datetime NULL,
  CROUTING_ENTITY_TYPE varchar(256) NULL,
  CBOM_ID bigint NULL COMMENT "物料清单ID",
  CENTITY_TYPE varchar(256) NULL COMMENT "实体类型",
  CBIZ_ORG_ID bigint NULL COMMENT "所属组织ID",
  CBIZ_ORG_NAME varchar(512) NULL COMMENT "所属组织ID",
  CPLANNED_END_TIME datetime NULL COMMENT "计划结束时间",
  CCODE varchar(512) NULL COMMENT "编码",
  CLIFECYCLE_STATE varchar(256) NULL COMMENT "生命周期状态 [MO_020_PUBLISHED:已发布, MO_070_STORED:已入库, MO_010_CREATED:已创建, MO_030_EXPANDED:已展开, MO_050_STARTED:已开工, MO_060_FINISHED:已完工, MO_080_CLOSED:已关闭]",
  CLIFECYCLE_TEMPLATE varchar(512) NULL COMMENT "生命周期模板",
  CSCHEDULED_END_TIME datetime NULL,
  CPLANNER_ENTITY_TYPE varchar(256) NULL,
  CSOFT_DELETE_FLAG int NULL COMMENT "软删除标记",
  CSPECIFIED_PLANNED_END_TIME datetime NULL COMMENT "指定计划结束时间",
  CAPPLIED_IN_STORAGE_QTY decimal(38,9) NULL COMMENT "已申请合格入库数量",
  CACTUAL_START_TIME datetime NULL COMMENT "实际开始时间",
  CSPECIFIED_PLANNED_START_TIME datetime NULL COMMENT "指定计划开始时间",
  CCONTROL_STATUS varchar(256) NULL COMMENT "控制状态 [CS_020_PAUSED:暂停, CS_010_NORMAL:正常, CS_030_TERMINATION:终止, CS_030_CANCEL:取消, CS_040_CANCEL:已取消]",
  CMANU_TYPE varchar(256) NULL COMMENT "订单制造类型 [MT_040_REPAIR:返修, MT_030_REWORK:返工, MT_020_TRANSFER:转工, MT_010_STANDARD:标准]",
  CSERIAL_NUMBER_FLAG varchar(1) NULL COMMENT "启用序列号标记",
  CSECURITY_LEVEL varchar(256) NULL COMMENT "密级",
  CPROD_ORDER_ID bigint NULL COMMENT "生产订单ID",
  CNAME varchar(512) NULL COMMENT "名称",
  CROUTING_ID bigint NULL COMMENT "工艺路线ID",
  CUNIT varchar(255) NULL COMMENT "计量单位",
  CREMARK varchar(1024) NULL COMMENT "备注",
  CMODIFIER_ID bigint NULL COMMENT "修改者ID",
  CMODIFIER_ENTITY_TYPE varchar(256) NULL,
  CLATEST_UPDATE_TIME datetime NULL COMMENT "最近修改时间",
  CBIZ_ORG_ENTITY_TYPE varchar(256) NULL
) ENGINE=OLAP
UNIQUE KEY(CID)
COMMENT '制造订单'
DISTRIBUTED BY HASH(CID) BUCKETS 10
PROPERTIES (
"replication_allocation" = "tag.location.default: 1",
"min_load_replica_num" = "-1",
"is_being_synced" = "false",
"storage_medium" = "hdd",
"storage_format" = "V2",
"inverted_index_storage_format" = "V2",
"compression" = "LZ4",
"enable_unique_key_merge_on_write" = "true",
"light_schema_change" = "true",
"disable_auto_compaction" = "false",
"enable_single_replica_compaction" = "false",
"group_commit_interval_ms" = "10000",
"group_commit_data_bytes" = "134217728",
"enable_mow_light_delete" = "false"
);

insert into bi.MOM_MANU_ORDER_WIDE
select t1.CID
  ,t1.CMATERIAL_ENTITY_TYPE
  ,t1.CBOM_ENTITY_TYPE
  ,t1.CSCHEDULED_FLAG
  ,t1.CPROD_ORDER_ENTITY_TYPE
  ,t1.CMATERIAL_ID
  ,t1.CBATCH_NUMBER
  ,t1.CPROJECT_NUMBER
  ,t1.CFACTORY_ID
  ,t2.CNAME as CFACTORY_NAME
  ,t1.COUTSOURCING_FLAG
  ,t1.CFACTORY_ENTITY_TYPE
  ,t1.CPRIORITY
  ,t1.CSPLIT_CARD_FLAG
  ,t1.CACTUAL_END_TIME
  ,t1.CPREPARATION_PLAN_ENTITY_TYPE
  ,t1.CPREPARATION_PLAN_ID
  ,t1.CPLANNER_ID
  ,t1.CDRAWING_NUMBER
  ,t1.CSCRAPPED_QTY
  ,t1.CCREATE_TIME
  ,t1.CCREATOR_ID
  ,t1.CPLANNED_START_TIME
  ,t1.CCREATOR_ENTITY_TYPE
  ,t1.CENV
  ,t1.CQUALIFIED_QTY
  ,t1.CMANU_MODEL
  ,t1.CPLANNED_QTY
  ,t1.CSCHEDULED_START_TIME
  ,t1.CROUTING_ENTITY_TYPE
  ,t1.CBOM_ID
  ,t1.CENTITY_TYPE
  ,t1.CBIZ_ORG_ID
  ,t3.CNAME as CBIZ_ORG_NAME
  ,t1.CPLANNED_END_TIME
  ,t1.CCODE
  ,t1.CLIFECYCLE_STATE
  ,t1.CLIFECYCLE_TEMPLATE
  ,t1.CSCHEDULED_END_TIME
  ,t1.CPLANNER_ENTITY_TYPE
  ,t1.CSOFT_DELETE_FLAG
  ,t1.CSPECIFIED_PLANNED_END_TIME
  ,t1.CAPPLIED_IN_STORAGE_QTY
  ,t1.CACTUAL_START_TIME
  ,t1.CSPECIFIED_PLANNED_START_TIME
  ,t1.CCONTROL_STATUS
  ,t1.CMANU_TYPE
  ,t1.CSERIAL_NUMBER_FLAG
  ,t1.CSECURITY_LEVEL
  ,t1.CPROD_ORDER_ID
  ,t1.CNAME
  ,t1.CROUTING_ID
  ,t1.CUNIT
  ,t1.CREMARK
  ,t1.CMODIFIER_ID
  ,t1.CMODIFIER_ENTITY_TYPE
  ,t1.CLATEST_UPDATE_TIME
  ,t1.CBIZ_ORG_ENTITY_TYPE
from target.MOM_MANU_ORDER t1 
left join target.SYS_BIZ_ORG t2 on t1.CFACTORY_ID = t2.CID
left join target.SYS_BIZ_ORG t3 on t1.CBIZ_ORG_ID = t3.CID
where t1.CSOFT_DELETE_FLAG=0